apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-page-green
  namespace: status-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: status-page
      env: green
  template:
    metadata:
      labels:
        app: status-page
        env: green
    spec:
      containers:
      - name: web
        image: status-page:v2
        imagePullPolicy: Never # Si usas Minikube localmente
        env:
        - name: APP_VERSION
          value: "v2"
        - name: DATA_DIR
          value: "/data"
        volumeMounts:
        - name: datos
          mountPath: /data
        ports:
        - containerPort: 3000
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 20
      volumes:
      - name: datos
        persistentVolumeClaim:
          claimName: status-page-data