apiVersion: v1
kind: Service
metadata:
  name: status-page-service
  namespace: status-project
spec:
  type: NodePort
  selector:
    app: status-page
    env: blue   # <--- CAMBIAR A 'green' PARA REALIZAR EL BLUE/GREEN SWITCH
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080