apiVersion: v1
kind: Service
metadata:
  name: status-page-service
  namespace: status-project
spec:
  type: NodePort
  selector:
    app: status-page
    env: green   # <--- CAMBIAR A 'blue' PARA VOLVER ATRAS (rollback instantaneo)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080